In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.randn(5)

array([0.03553376, 0.90388751, 0.81093495, 0.53838268, 0.45627787])

In [20]:
np.random.randn(5,5)

array([[ 1.19946777, -0.65192038,  0.68117951, -1.00156651, -0.13751856],
       [ 1.27429277, -0.95324626,  0.66338481,  0.12253164, -0.0914797 ],
       [ 0.57764466, -0.08200026,  0.60420338, -0.27072153, -0.45682351],
       [-0.68109116, -0.99889703, -2.79026049, -1.45031318, -0.22524022],
       [ 0.47337372, -1.67396943, -0.3475386 ,  0.17847796,  1.14746192]])

In [21]:
np.random.rand(5)

array([0.87743406, 0.29910637, 0.38390098, 0.01301796, 0.642553  ])

In [22]:
np.random.rand(5,5)

array([[0.13127857, 0.10693783, 0.9347947 , 0.04424916, 0.58145128],
       [0.63659269, 0.98946193, 0.93038907, 0.31258627, 0.54826921],
       [0.5314165 , 0.75516457, 0.45909462, 0.37887865, 0.37960851],
       [0.48909078, 0.88139038, 0.21064406, 0.11579019, 0.45777798],
       [0.30734465, 0.07589822, 0.16984387, 0.18585702, 0.58015554]])

In [23]:
np.random.randint(1,100,)

53

In [24]:
np.random.randint(1,100,50)

array([43, 96, 71, 46, 56,  6, 12, 14, 56, 23,  3, 57, 46, 51, 92, 76, 79,
       17, 88, 10, 49, 15, 78, 12, 50, 51, 84, 58, 38, 16, 54, 81, 89, 34,
       47, 84, 27,  3, 78, 61, 28, 90, 42, 86, 56, 95, 21, 39, 42, 13])

In [25]:
arr = np.arange(25)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr = np.random.randint(0,50,10)

In [28]:
ranarr

array([33, 20, 44, 46,  5, 12, 44, 25, 47, 13])

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
ranarr

array([33, 20, 44, 46,  5, 12, 44, 25, 47, 13])

In [31]:
ranarr.max()

47

In [32]:
ranarr.min()

5

In [34]:
ranarr

array([33, 20, 44, 46,  5, 12, 44, 25, 47, 13])

In [35]:
ranarr.argmax()

8

In [36]:
ranarr.argmin()

4

In [37]:
arr.shape

(25,)

In [38]:
arr = arr.reshape(5,5)

In [39]:
arr.shape

(5, 5)

In [41]:
arr.dtype

dtype('int32')